name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

